### ISSUE TITLE
Unable to use donwload the archetype

### ISSUE THREAD

**Issue by dcremonini** [JorgeRojasDev/hexagonal-reactive-archetype#1]
Hi Jorge,
I tried to use this archetype but it looks like it's not published.

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-archetype-plugin:3.2.0:generate (default-cli) on project standalone-pom: The desired archetype does not exist (io.github.jorgerojasdev:hexagonal-reactive-archetype:0.0.1) -> [Help 1]

Please may you have a look?

Thank you
Daniele

**Comment by JorgeRojasDev** [comment]
Hi Daniele, 
Thanks for contact me, this repository is not uploaded to maven central, for that reason, you must download the project first, do maven install as in the instructions and run mvn: archetype, when it cannot find the repository in central it uses our local catalog.

If you need any additional help, we are in contact,

Cheers,
Jorge

**Comment by dcremonini** [comment]
Hi Jorge,
Today I tried once again following the instructions in the README.md and it works.

Maybe I did something wrong because I found that actually you published something but under a different name.

If you have a look in the [Maven Archetype Catalog](https://repo1.maven.org/maven2/archetype-catalog.xml) you can find this artifact:

```
<archetype>
   <groupId>io.github.jorgerojasdev</groupId>
   <artifactId>hexagonal-reactive</artifactId>
   <version>0.0.1</version>
   <description>hexagonal-reactive</description>
</archetype>
```
and this is the one that doesn't work.

Thank you
Daniele
